AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  LinearAutomationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: nodejs20.x
      CodeUri: .
      Timeout: 30
      Environment:
        Variables:
          LINEAR_API_KEY: !Ref LinearApiKey
          LINEAR_WEBHOOK_SIGNING_SECRET: !Ref LinearWebhookSigningSecret
      FunctionUrlConfig:
        AuthType: NONE
      EventInvokeConfig:
        MaximumRetryAttempts: 0

Parameters:
  LinearApiKey:
    Type: String
    Description: Linear API Key
  LinearWebhookSigningSecret:
    Type: String
    Description: Linear Webhook signing secret